### ISSUE TITLE
Question about node authentication for pulling image from private ECR registry

### ISSUE THREAD

**Issue by maxmele** [aws-samples/aws-iam-ra-for-kubernetes#2]
Hello,

First, thank you for providing this guide on implementing AWS roles anywhere with HashiCorp Vault. I think it is a really interesting solution that can help us a lot in our company. However, there is one thing I don't understand.

The authentication process to AWS is handled within the init container itself. However, I noticed that the init container uses an image hosted in a private ECR registry. Since the cluster is outside AWS, how does the kubelet of the node authenticate to AWS to pull the init container image from the private ECR registry? 

Thanks in advance,

**Comment by likku123** [comment]
I believe one has to make this image public in your respective aws account.

**Comment by jicowan** [comment]
@maxmele You can build the image and push it to your preferred repository. You don't have to pull from ECR. I believe the Dockerfile for creating the image is in this repository.
